export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	SET_VALUE: 'SET_VALUE',
	SET_MODE_CHART: 'SET_MODE_CHART',
};
